
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wwojqnkqtcmkgaxgmbqg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind3b2pxbmtxdGNta2dheGdtYnFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3NjI5MjUsImV4cCI6MjA1NzMzODkyNX0.Rn9rFYX1DdTDzOPhtCfol1uBqIYVvmNrPhnv51JOiO4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Function to fetch secrets (would be used for CopilotKit API key)
export const getCopilotApiKey = async () => {
  try {
    const { data, error } = await supabase.functions.invoke('get-secret', {
      body: { key: 'COPILOTKIT_PUBLIC_API_KEY' }
    });
    
    if (error) throw error;
    return data.value;
  } catch (error) {
    console.error('Error fetching CopilotKit API key:', error);
    return null;
  }
};
